export const styles = {
  panel: {
    background: 'white',
    borderRadius: '0.5rem',
    border: '1px solid #e5e7eb',
    padding: '1.5rem',
  },
  panelHeader: {
    marginBottom: '1.5rem',
    paddingBottom: '1rem',
    borderBottom: '1px solid #e5e7eb',
  },
  panelTitle: {
    fontSize: '1.25rem',
    fontWeight: 600,
    margin: '0 0 0.5rem 0',
  },
  subtitle: {
    fontSize: '0.875rem',
    color: '#6b7280',
    margin: 0,
  },
  tabs: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1rem',
    borderBottom: '1px solid #e5e7eb',
  },
  tab: {
    padding: '0.5rem 1rem',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    fontWeight: 500,
    color: '#6b7280',
  },
  activeTab: {
    padding: '0.5rem 1rem',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid #8b5cf6',
    cursor: 'pointer',
    fontWeight: 500,
    color: '#8b5cf6',
  },
  codeBlock: {
    background: '#1f2937',
    color: '#e5e7eb',
    padding: '1rem',
    borderRadius: '0.375rem',
    fontFamily: 'monospace',
    fontSize: '0.875rem',
    overflowX: 'auto' as const,
    maxHeight: '600px',
    overflowY: 'auto' as const,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-word' as const,
  },
  composerContainer: {
    maxHeight: '600px',
    overflowY: 'auto' as const,
  },
  divider: {
    borderTop: '2px solid #e5e7eb',
    margin: '1.5rem 0',
    padding: '1.5rem 0 0 0',
  },
  feedHeader: {
    fontSize: '1.125rem',
    fontWeight: 600,
    marginBottom: '1rem',
    color: '#111827',
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '2rem',
    color: '#6b7280',
  },
  clearButton: {
    padding: '0.375rem 0.75rem',
    background: 'none',
    border: '1px solid #e5e7eb',
    borderRadius: '0.375rem',
    cursor: 'pointer',
    fontSize: '0.75rem',
    color: '#6b7280',
    marginLeft: '0.5rem',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  hidden: {
    display: 'none',
  },
  eventPreviewLabel: {
    fontSize: '0.75rem',
    color: '#9ca3af',
    marginBottom: '0.5rem',
    fontStyle: 'italic' as const,
  },
  replyPanel: {
    border: '1px solid #e5e7eb',
    borderRadius: '0.5rem',
    background: '#f9fafb',
    padding: '1rem',
    marginBottom: '1rem',
  },
  replyGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.75rem',
    marginTop: '0.75rem',
  },
  replyField: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.25rem',
  },
  replyLabel: {
    fontSize: '0.8125rem',
    fontWeight: 500,
    color: '#374151',
  },
  replyInput: {
    width: '100%',
    padding: '0.5rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.375rem',
    fontSize: '0.875rem',
  },
  replyMeta: {
    fontSize: '0.75rem',
    color: '#6b7280',
    marginTop: '0.5rem',
  },
  actionButton: {
    padding: '0.375rem 0.75rem',
    border: '1px solid #8b5cf6',
    borderRadius: '0.375rem',
    background: 'white',
    color: '#8b5cf6',
    fontSize: '0.75rem',
    fontWeight: 600,
    cursor: 'pointer',
    marginRight: '0.5rem',
    marginBottom: '0.5rem',
  },
} as const;
