import type { CSSProperties } from 'react';

export const styles = {
  panel: {
    background: 'white',
    borderRadius: '0.5rem',
    border: '1px solid #e5e7eb',
    overflow: 'hidden',
  },
  tabs: {
    display: 'flex',
    borderBottom: '1px solid #e5e7eb',
  },
  tab: (active: boolean): CSSProperties => ({
    padding: '0.75rem 1.25rem',
    fontSize: '0.875rem',
    fontWeight: active ? 600 : 400,
    color: active ? '#7c3aed' : '#6b7280',
    borderBottom: active ? '2px solid #7c3aed' : '2px solid transparent',
    cursor: 'pointer',
    background: 'none',
    border: 'none',
    marginBottom: '-1px',
  }),
  body: {
    padding: '1.25rem',
  },
  infoBox: {
    background: '#f5f3ff',
    border: '1px solid #ddd6fe',
    borderRadius: '0.375rem',
    padding: '0.75rem 1rem',
    fontSize: '0.8rem',
    color: '#5b21b6',
    marginBottom: '1rem',
  },
  eventCard: {
    background: '#1f2937',
    borderRadius: '0.375rem',
    padding: '1rem',
    marginTop: '0.75rem',
  },
  eventJson: {
    color: '#d1fae5',
    fontFamily: "'Monaco', 'Courier New', monospace",
    fontSize: '0.72rem',
    whiteSpace: 'pre-wrap' as const,
    margin: 0,
    overflowX: 'auto' as const,
  },
  sectionTitle: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#9ca3af',
    marginBottom: '0.5rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  searchRow: {
    display: 'flex',
    gap: '0.5rem',
    padding: '1rem 1.25rem 0.75rem',
  },
  input: {
    flex: 1,
    padding: '0.5rem 0.75rem',
    border: '1px solid #d1d5db',
    borderRadius: '0.375rem',
    fontSize: '0.875rem',
  },
  button: {
    padding: '0.5rem 1rem',
    background: '#7c3aed',
    color: 'white',
    border: 'none',
    borderRadius: '0.375rem',
    fontSize: '0.875rem',
    fontWeight: 500,
    cursor: 'pointer',
  },
  smallButton: {
    padding: '0.25rem 0.6rem',
    background: 'white',
    color: '#5b21b6',
    border: '1px solid #ddd6fe',
    borderRadius: '0.375rem',
    fontSize: '0.75rem',
    cursor: 'pointer',
  },
  list: {
    maxHeight: '240px',
    overflowY: 'auto' as const,
    borderTop: '1px solid #e5e7eb',
    borderBottom: '1px solid #e5e7eb',
  },
  listItem: (selected: boolean): CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    width: '100%',
    padding: '0.55rem 1.25rem',
    border: 'none',
    borderBottom: '1px solid #f3f4f6',
    background: selected ? '#f5f3ff' : 'white',
    boxShadow: selected ? 'inset 3px 0 0 #7c3aed' : 'none',
    textAlign: 'left',
    cursor: 'pointer',
    font: 'inherit',
  }),
  itemMain: {
    flex: 1,
    minWidth: 0,
  },
  itemTitle: {
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#111827',
  },
  itemMeta: {
    fontSize: '0.72rem',
    color: '#6b7280',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  status: {
    padding: '0.6rem 1.25rem',
    fontSize: '0.8rem',
    color: '#6b7280',
  },
  entityHeader: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '0.5rem',
    padding: '0.75rem 1.25rem 0',
  },
  entityTitle: {
    fontSize: '1rem',
    fontWeight: 600,
    color: '#111827',
    margin: 0,
  },
  mono: {
    fontFamily: 'monospace',
    fontSize: '0.75rem',
    color: '#6b7280',
  },
} as const;
